'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property frmGravityNetPos() As Global.System.Drawing.Point
            Get
                Return CType(Me("frmGravityNetPos"),Global.System.Drawing.Point)
            End Get
            Set
                Me("frmGravityNetPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800, 500")>  _
        Public Property frmGravityNetTaille() As Global.System.Drawing.Size
            Get
                Return CType(Me("frmGravityNetTaille"),Global.System.Drawing.Size)
            End Get
            Set
                Me("frmGravityNetTaille") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bAffichageBanniere() As Boolean
            Get
                Return CType(Me("bAffichageBanniere"),Boolean)
            End Get
            Set
                Me("bAffichageBanniere") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gravity.Net  Screen Saver")>  _
        Public Property TxtBanniere() As String
            Get
                Return CType(Me("TxtBanniere"),String)
            End Get
            Set
                Me("TxtBanniere") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Images\Space\*.jpg")>  _
        Public Property FiltreFichiersImgFond() As String
            Get
                Return CType(Me("FiltreFichiersImgFond"),String)
            End Get
            Set
                Me("FiltreFichiersImgFond") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Images\Star_*.*")>  _
        Public Property FiltreFichiersImgSprite() As String
            Get
                Return CType(Me("FiltreFichiersImgSprite"),String)
            End Get
            Set
                Me("FiltreFichiersImgSprite") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property DegreRacine() As Integer
            Get
                Return CType(Me("DegreRacine"),Integer)
            End Get
            Set
                Me("DegreRacine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DegreRacine_bRnd() As Boolean
            Get
                Return CType(Me("DegreRacine_bRnd"),Boolean)
            End Get
            Set
                Me("DegreRacine_bRnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property DegreRacineRndMax() As Integer
            Get
                Return CType(Me("DegreRacineRndMax"),Integer)
            End Get
            Set
                Me("DegreRacineRndMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property DegreRacine2() As Integer
            Get
                Return CType(Me("DegreRacine2"),Integer)
            End Get
            Set
                Me("DegreRacine2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DegreRacine2_bRnd() As Boolean
            Get
                Return CType(Me("DegreRacine2_bRnd"),Boolean)
            End Get
            Set
                Me("DegreRacine2_bRnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property DegreRacine2RndMax() As Integer
            Get
                Return CType(Me("DegreRacine2RndMax"),Integer)
            End Get
            Set
                Me("DegreRacine2RndMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bMasseSym() As Boolean
            Get
                Return CType(Me("bMasseSym"),Boolean)
            End Get
            Set
                Me("bMasseSym") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bMasseSym_bRnd() As Boolean
            Get
                Return CType(Me("bMasseSym_bRnd"),Boolean)
            End Get
            Set
                Me("bMasseSym_bRnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property b3D() As Boolean
            Get
                Return CType(Me("b3D"),Boolean)
            End Get
            Set
                Me("b3D") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property b3D_bRnd() As Boolean
            Get
                Return CType(Me("b3D_bRnd"),Boolean)
            End Get
            Set
                Me("b3D_bRnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bChocs() As Boolean
            Get
                Return CType(Me("bChocs"),Boolean)
            End Get
            Set
                Me("bChocs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bChocs_bRnd() As Boolean
            Get
                Return CType(Me("bChocs_bRnd"),Boolean)
            End Get
            Set
                Me("bChocs_bRnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bCercle() As Boolean
            Get
                Return CType(Me("bCercle"),Boolean)
            End Get
            Set
                Me("bCercle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property ForceGravitation() As Integer
            Get
                Return CType(Me("ForceGravitation"),Integer)
            End Get
            Set
                Me("ForceGravitation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DelaiMiliSec() As Integer
            Get
                Return CType(Me("DelaiMiliSec"),Integer)
            End Get
            Set
                Me("DelaiMiliSec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property TempsMaxScenarioSec() As Integer
            Get
                Return CType(Me("TempsMaxScenarioSec"),Integer)
            End Get
            Set
                Me("TempsMaxScenarioSec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bImageFond() As Boolean
            Get
                Return CType(Me("bImageFond"),Boolean)
            End Get
            Set
                Me("bImageFond") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bMAJToutLEcran() As Boolean
            Get
                Return CType(Me("bMAJToutLEcran"),Boolean)
            End Get
            Set
                Me("bMAJToutLEcran") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bMAJGroupeSprites() As Boolean
            Get
                Return CType(Me("bMAJGroupeSprites"),Boolean)
            End Get
            Set
                Me("bMAJGroupeSprites") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bNePasInitFond() As Boolean
            Get
                Return CType(Me("bNePasInitFond"),Boolean)
            End Get
            Set
                Me("bNePasInitFond") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bNePasBufferiserGr() As Boolean
            Get
                Return CType(Me("bNePasBufferiserGr"),Boolean)
            End Get
            Set
                Me("bNePasBufferiserGr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bFondUni() As Boolean
            Get
                Return CType(Me("bFondUni"),Boolean)
            End Get
            Set
                Me("bFondUni") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bFondDegrade() As Boolean
            Get
                Return CType(Me("bFondDegrade"),Boolean)
            End Get
            Set
                Me("bFondDegrade") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property b3D_bPlanetesAxeV() As Boolean
            Get
                Return CType(Me("b3D_bPlanetesAxeV"),Boolean)
            End Get
            Set
                Me("b3D_bPlanetesAxeV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property b3D_bPlanetesAxeV_bRnd() As Boolean
            Get
                Return CType(Me("b3D_bPlanetesAxeV_bRnd"),Boolean)
            End Get
            Set
                Me("b3D_bPlanetesAxeV_bRnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property b3D_iNbPlanetesMaxAxeV() As Integer
            Get
                Return CType(Me("b3D_iNbPlanetesMaxAxeV"),Integer)
            End Get
            Set
                Me("b3D_iNbPlanetesMaxAxeV") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.My.MySettings
            Get
                Return Global.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
